spring:
  cloud:
    nacos:
      discovery:
        namespace: dev
        group: DEV_GROUP

grpc:
  server:
    port: 9091

logging:
  level:
    org.tripsphere.note: DEBUG

app:
  ai:
    enabled: false