networks:
  default:
    name: tripsphere
    driver: bridge

services:
  # Nacos
  nacos:
    image: nacos/nacos-server:v2.5.1
    container_name: nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8848:8848"
      - "9848:9848"

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.86.0
    container_name: otel-collector
    command: ["--config=/etc/otelcol-config.yaml"]
    volumes:
      - ./otel-collector/otelcol-config.yaml:/etc/otelcol-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"

  # RocketMQ Name Server
  rmq-namesrv:
    image: apache/rocketmq:5.3.2
    container_name: rmq-namesrv
    ports:
      - "9876:9876"
    command: sh mqnamesrv

  # RocketMQ Broker
  rmq-broker:
    image: apache/rocketmq:5.3.2
    container_name: rmq-broker
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    environment:
      - NAMESRV_ADDR=rmq-namesrv:9876
    depends_on:
      - rmq-namesrv
    command: sh mqbroker

  # RocketMQ Proxy
  rmq-proxy:
    image: apache/rocketmq:5.3.2
    container_name: rmq-proxy
    depends_on:
      - rmq-broker
      - rmq-namesrv
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: on-failure
    environment:
      - NAMESRV_ADDR=rmq-namesrv:9876
    command: sh mqproxy

  # RocketMQ Dashboard
  rmq-dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rmq-dashboard
    ports:
      - "8082:8082"
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=rmq-namesrv:9876
    depends_on:
      - rmq-namesrv

  # MongoDB
  mongodb:
    image: mongodb/mongodb-community-server:8.0-ubi8
    container_name: mongodb
    user: root  # r/w permissions to the mounted directory
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: fudanse
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongodb:/data/db

  # MySQL
  mysql:
    image: mysql:8.4.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: fudanse
      TZ: Asia/Shanghai
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    healthcheck:
      test: mysql --user=root --password=fudanse --execute="SHOW DATABASES;"
      interval: 30s
      timeout: 5s
      retries: 5

  # MinIO
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ./volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Qdrant
  qdrant:
    image: qdrant/qdrant:v1.16
    restart: always
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./volumes/qdrant:/qdrant/storage

  # Neo4j
  neo4j:
    image: neo4j:5.26.19
    container_name: neo4j
    volumes:
      - ./volumes/neo4j/logs:/logs
      - ./volumes/neo4j/config:/config
      - ./volumes/neo4j/data:/data
      - ./volumes/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/fudanse@fudan.edu.cn
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always

  # Redis
  redis:
    image: redis:8.4
    container_name: redis
    volumes:
      - ./volumes/redis/data:/data
    ports:
      - "6379:6379"
    restart: "always"

configs:
  qdrant_config:
    content: |
      log_level: INFO