[config]
    [mysql]
        [mysql.read]
        addr = "47.120.37.103:3306"
        user = "read_user"
        pass = "read_password"
        name = "app_database_read"
        [mysql.write]
        addr = "47.120.37.103:3306"
        user = "root"
        pass = "123456"
        name = "benchmark?parseTime=true"
        [mysql.base]
        maxOpenConn = 100
        maxIdleConn = 10
        connMaxLifeTime = "1h"
    [rocketmq]
        groupNname = ""
        endpoint = "47.120.37.103:8081"
        accessKey = ""
        secretKey = ""
